* AutonomousSoftwareOrg
Smart Contract Based Autonomous Organization for Sustainable Software

** About
AutonomousSoftwareOrg is a Solidity smart contract that implements an autonomous software organization to be used by software developers.

*Design of a Smart Contract Based Autonomous Organization for Sustainable Software Paper Link:* [[https://ieeexplore.ieee.org/document/8109181]]

It contributes:
1. Design and implement a smart contract called AutonomousSoftwareOrg, which is a DAO-based smart contract for software development, sustainable and reproducible software, and advancements in e-Science.
2. Recording of software execution traces on the blockchain. Each trace consists of a linkage of input and output data files of each software execution.
3. Software tools for analysis of software executions.

*** AutonomousSoftwareOrg Smart Contract Deployed Addresses
#+begin_src yaml
bloxberg:
    address: '0x450eb7EC90418E9D768f85Ffa1b29187AD57251a'
    tx_hash: '0xc07dc41d0e435728a5e405a8697470c57db19db26a16aac6c97bdb1e81110359'
#+end_src
